version: '3.9'

services:
  news_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  news_web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/news_drf
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_data: