FROM python:3.10.4 as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/news_drf

RUN apt-get update
RUN apt-get upgrade -y && apt-get -y install postgresql gcc python3-dev musl-dev

RUN pip install --upgrade pip

COPY . .

COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/news_drf/wheels -r requirements.txt

FROM python:3.10.4

RUN mkdir -p /home/app

RUN groupadd app
RUN useradd -m -g app user -p PASSWORD
RUN usermod -aG app user

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

RUN apt-get update \
    && apt-get install -y netcat

COPY --from=builder /usr/src/news_drf/wheels /wheels
COPY --from=builder /usr/src/news_drf/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY ./entrypoint-prod.sh $APP_HOME

COPY . $APP_HOME

RUN chown -R user:app $APP_HOME

USER user

ENTRYPOINT ["/home/app/web/entrypoint-prod.sh"]
